### ISSUE TITLE
Crash when using multirun : RuntimeError: Your newdatapoints are to wide for the current knots !

### ISSUE THREAD

**Issue by martin-millon** [COSMOGRAIL/PyCS#23]
This cause the crash of all the process because one curve raises the error : 
`RuntimeError: Your newdatapoints are to wide for the current knots !`   in sim.run.spl.update() '

Would it be possible to add an exception if only one of 800 curves you are optimizing is crashing? 
Or maybe changing the dpmethod from "leave" to "extadj" or "stretch" would avoid this?

**Comment by vbonvin** [comment]
Not sure what you are talking about because sim.run.spl.update() does not exist.

On the principles of adding an exception: if only one/two fit fails, then it's reasonable to discard the problematic curves, but you want to avoid having a significant amount of estimates crashing without you knowing about it - which might be a sign that something is wrong with the optimisation you are currently working with and you want to be aware of that.

One way of circumventing that is to wrap the problematic piece of code in a try/except statement, where you increment a counter and a warning each time an error should be raised. If the counter exceeds a certain value (say 2% of your total number of mocks), then you raise the RuntimeError.

**Comment by martin-millon** [comment]
Sorry in sim.run.spl.updatedp() 

In my case, it's happened in one case out 8000 curves. Maybe it would be better to choose another dpmethod then, but I don't know what this would imply. 

Or to crash only one process and go to the next .workingon file without crashing the other threads.
